sudo: false
language: node_js
node_js:
  - '5'
cache:
  directories:
    - node_modules
before_script:
  - npm prune
notifications:
  email: false
script:
  - npm run test
after_success:
  - npm run coverage
branches:
  only:
    - master