sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
  - master
notifications:
  email: false
node_js:
  - '5'
before_install:
  - npm i -g npm@^3.7.3
before_script:
  - npm prune
script: 
  - npm run test
after_success:
  - npm run coverage      