module.exports = { context: '__dirname',
  entry: 'todo',
  ouput: 'todo',
  module: 'todo',
  resolve: 'todo',
  resolveLoader: 'todo',
  externals: 'todo',
  target: 'todo',
  bail: 'todo',
  profil: 'todo',
  cache: 'todo',
  debug: 'todo',
  devtool: 'todo',
  devServer: 'todo',
  node: 'todo',
  amd: 'todo',
  loader: 'todo',
  recordsPath: 'todo',
  recordsInputPath: 'todo',
  recordsOutputPath: 'todo',
  plugins: 'todo' }
